name: Deploy to GCP Workbench

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify Terraform version >= 1.0.0

      - name: Verify Terraform Version
        run: terraform version

      - name: Terraform Init
        run: terraform init -chdir=./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -chdir=./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_JSON }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Copy files to GCP Workbench
        run: |
          gcloud compute scp --recurse ./notebooks/ ./data/ ./scripts/ ./requirements.txt my-workbench-instance:/home/jupyter/ --zone=us-central1-a

      - name: Run setup script on Workbench
        run: |
          gcloud compute ssh my-workbench-instance --zone=us-central1-a --command="chmod +x /home/jupyter/scripts/setup.sh && bash /home/jupyter/scripts/setup.sh"